---
title: "Sample size calculator"
output: 
  flexdashboard::flex_dashboard:
    theme: flatly
    source_code: "http://devtools01.westat.com:8081/Statistics/basu/"
---

```{r, echo=FALSE}
library(flexdashboard)
library(htmltools)

tags$script(src="http://code.jquery.com/jquery-1.10.2.min.js")
tags$script(src="http://cdn.opencpu.org/opencpu-0.4.js")
tags$script(src="basu.js")
```

Column {.tabset}
-------------------------------------

### Proportions

<p><em>Leave empty the box that you want to calculate.</em></p>

```{r}
tags$div(class="form-group",
         tags$label("First proportion (or effect size)"),
         tags$input(class="form-control",
                    placeholder="First proportion (e.g., 0.8) or effect size",
                    id="p1"))

tags$div(class="form-group",
         tags$label("Second proportion"),
         tags$input(class="form-control",
                    placeholder="Second proportion (e.g., 0.2) or empty for effect size",
                    id="p2"))

tags$div(class="form-group",
         tags$label("Significance level"),
         tags$input(class="form-control",
                    placeholder="Alpha level as a proportion (e.g., 0.05)",
                    id="siglevel"))

tags$div(class="form-group", 
         tags$label("Power"),
         tags$input(class="form-control",
                    placeholder="Power as a proportion (e.g., 0.8)",
                    id="power"))

tags$div(class="form-group", id="isize",
         tags$label("Sample size"),
         tags$input(class="form-control", 
                    id="size1"))

tags$div(class="form-group", 
         tags$label("Design effect"),
         tags$input(class="form-control",
                    value="1",
                    type="number",
                    id="deff"))

tags$div(class="form-group",
         tags$label("Alternative hypothesis"),
         tags$select(class="form-control",                     
                     tags$option("Two sided",
                                 value="two.sided"),
                     tags$option("First proportion smaller than second",
                                 value="less"),
                     tags$option("First proportion greater than second",
                                 value="greater"),
                     id="alternative"))

tags$div(class="form-group",
         tags$label("Type of test"),
         tags$select(class="form-control",
                     tags$option("One sample", value="v.pwr.p.test"),
                     tags$option("Two samples", value="v.pwr.2p.test"),
                     id="pfunction"))

tags$button("Submit", type="submit", class="btn btn-primary", id="ptest")
```

### Means

<p><em>Leave empty the box that you want to calculate.</em></p>

```{r}
tags$div(class="form-group",
         tags$label("True difference"),
         tags$input(class="form-control",
                    placeholder="Effect size (Cohen's d)",
                    id="td"))

tags$div(class="form-group",
         tags$label("Significance level"),
         tags$input(class="form-control",
                    placeholder="Alpha level as a proportion (e.g., 0.05)",
                    id="tsiglevel"))

tags$div(class="form-group",
         tags$label("Power"),
         tags$input(class="form-control",
                    placeholder="Power as a proportion (e.g., 0.8)",
                    id="tpower"))

tags$div(class="form-group",
         tags$label("Sample size"),
         tags$input(class="form-control", 
                    id="tsize"))

tags$div(class="form-group", 
         tags$label("Design effect"),
         tags$input(class="form-control",
                    value="1",
                    id="tdeff"))

tags$div(class="form-group",
         tags$label("Alternative hypothesis"),
         tags$select(class="form-control",
                     tags$option("Two sided", value="two.sided"),
                     tags$option("Smaller than", value="less"),
                     tags$option("Greater than", value="greater"),
                     id="talternative"))

tags$div(class="form-group",
         tags$label("Type of t test"),
         tags$select(class="form-control",
                     tags$option("One sample", value="one.sample"),
                     tags$option("Two samples", value="two.sample"),
                     tags$option("Paired samples", value="paired"),
                     id="ttype"))

tags$button("Submit", type="submit", class="btn btn-primary", id="ttest")
```

### Correlations

<p><em>Leave empty the box that you want to calculate.</em></p>

```{r}
tags$div(class="form-group",
         tags$label("Correlation"),
         tags$input(class="form-control",
                    placeholder="Correlation coefficient",
                    id="rr"))

tags$div(class="form-group",
         tags$label("Significance level"),
         tags$input(class="form-control",
                    placeholder="Alpha level as a proportion (e.g., 0.05)",
                    id="rsiglevel"))

tags$div(class="form-group",
         tags$label("Power"),
         tags$input(class="form-control",
                    placeholder="Power as a proportion (e.g., 0.8)",
                    id="rpower"))

tags$div(class="form-group",
         tags$label("Sample size"),
         tags$input(class="form-control", 
                    id="rsize"))

tags$div(class="form-group",
         tags$label("Alternative hypothesis"),
         tags$select(class="form-control",
                     tags$option("Two sided", value="two.sided"),
                     tags$option("Smaller than", value="less"),
                     tags$option("Greater than", value="greater"),
                     id="ralternative"))

tags$button("Submit", type="submit", class="btn btn-primary", id="rtest")
```

### Effect sizes

```{r}
tags$div(class="form-group",
         tags$label("Test"),
         tags$select(class="form-control",
                     tags$option("Proportions", value="p"),
                     tags$option("t-test", value="t"),
                     tags$option("Correlation", value="r"),
                     id="cohentest"))

tags$div(class="form-group",
         tags$label("Effect size"),
         tags$select(class="form-control",
                     tags$option("Small", value="small"),
                     tags$option("Medium", value="medium"),
                     tags$option("Large", value="large"),
                     id="coheneffsize"))

tags$button("Submit", type="submit", class="btn btn-primary", id="cohensize")
```

Column
-------------------------------------

### Output

<table id="basuoutput">
<tbody>
</tbody>
</table> 
