---
title: "Basu! Sample size calculator"
output: 
  flexdashboard::flex_dashboard:
    theme: flatly
    source_code: "http://devtools01.westat.com:8081/rivero_g/basu/"
---

```{r, echo=FALSE}
library(flexdashboard)
library(htmltools)

tags$script(src="http://code.jquery.com/jquery-1.10.2.min.js")
tags$script(src="http://cdn.opencpu.org/opencpu-0.4.js")
tags$script(src="basu.js")
```

Column {.tabset}
-------------------------------------

### Proportions

<p><em>Leave empty the box that you want to calculate.</em></p>

```{r}
tags$div(class="form-group",
         tags$label("First proportion (or effect size)"),
         tags$input(class="form-control",
                    placeholder="First proportion (e.g., 0.8) or effect size",
                    type="number", min="0", max="1", step="0.001",
                    id="p1"))

tags$div(class="form-group",
         tags$label("Second proportion"),
         tags$input(class="form-control",
                    placeholder="Second proportion (e.g., 0.2)",
                    type="number", min="0", max="1", step="0.001",
                    id="p2"))

tags$div(class="form-group",
         tags$label("Significance level"),
         tags$input(class="form-control",
                    placeholder="Alpha level as a proportion (e.g., 0.05)",
                    type="number", min="0", max="1", step="0.001",
                    id="siglevel"))

tags$div(class="form-group", 
         tags$label("Power"),
         tags$input(class="form-control",
                    placeholder="Power as a proportion (e.g., 0.8)",
                    type="number", min="0", max="1", step="0.001",
                    id="power"))

tags$div(class="form-group", id="isize",
         tags$label("Sample size"),
         tags$input(class="form-control", 
                    type="number", min="0", step="1",
                    id="size1"))

tags$div(class="form-group",
         tags$label("Alternative hypothesis"),
         tags$select(class="form-control",                     
                     tags$option("Two sided",
                                 value="two.sided"),
                     tags$option("First proportion smaller than second",
                                 value="less"),
                     tags$option("First proportion greater than second",
                                 value="greater"),
                     id="alternative"))

tags$div(class="form-group",
         tags$label("Type of test"),
         tags$select(class="form-control",
                     tags$option("One sample", value="pwr.p.test"),
                     tags$option("Two samples", value="pwr.2p.test"),
                     ## tags$option("Two sample (different sizes)",
                     ##             value="pwr.2p2n.test"),                     
                     id="pfunction"))

tags$button("Submit", type="submit", class="btn btn-primary", id="ptest")
```

### Means

<p><em>Leave empty the box that you want to calculate.</em></p>

```{r}
tags$div(class="form-group",
         tags$label("True difference"),
         tags$input(class="form-control",
                    placeholder="Effect size (Cohen's d)",
                    type="number", step="0.001",
                    id="td"))

tags$div(class="form-group",
         tags$label("Significance level"),
         tags$input(class="form-control",
                    placeholder="Alpha level as a proportion (e.g., 0.05)",
                    type="number", min="0", max="1", step="0.001",
                    id="tsiglevel"))

tags$div(class="form-group",
         tags$label("Power"),
         tags$input(class="form-control",
                    placeholder="Power as a proportion (e.g., 0.8)",
                    type="number", min="0", max="1", step="0.001",
                    id="tpower"))

tags$div(class="form-group",
         tags$label("Sample size"),
         tags$input(class="form-control", 
                    type="number", min="0", step="1",
                    id="tsize"))

tags$div(class="form-group",
         tags$label("Alternative hypothesis"),
         tags$select(class="form-control",
                     tags$option("Two sided", value="two.sided"),
                     tags$option("Smaller than", value="less"),
                     tags$option("Greater than", value="greater"),
                     id="talternative"))

tags$div(class="form-group",
         tags$label("Type of t test"),
         tags$select(class="form-control",
                     tags$option("One sample", value="one"),
                     tags$option("Two samples", value="two"),
                     tags$option("Paired samples", value="paired"),
                     id="ttype"))

tags$button("Submit", type="submit", class="btn btn-primary", id="ttest")
```

Column 
-------------------------------------

### Output

<table id="basuoutput">
<tbody>
</tbody>
</table> 

